port: 3000

redis:
  host: localhost
  port: 6379

logs:
  console: true
  app: "true"
  error: "true"

urls:
  triage: /triage
  rolo: https://www.rolouat.gro.gov.uk/gro/content/certificates/Login.asp
  help: /help

one-login:
  url: "https://oidc.integration.account.gov.uk"
  client_id: "PLACEHOLDER"
  authorize: /authorize?response_type=<%= responseType %>&scope=<%= scope %>&client_id=<%= clientId %>&request=<%= requestParam %>
  logout: /logout?id_token_hint=<%= idToken %>&post_logout_redirect_uri=<%= logoutRedirectUri %>&state=<%= state %>
  redirect_uri: "http://localhost:3000/user-details"
  logout_redirect_uri: "http://localhost:3000"
  private-key: ""

featureFlags:
  oneLogin: false

e-commerce:
  client_id: ""
  tenant_id: ""
  authority:  ""
  client_secret: ""
  retail_server_url: ""
  channel_id: ""
  operating_unit_number: ""
  cache_location: ""
